(function(g){var window=this;'use strict';var hs=function(b,W){if(!Number.isFinite(b))return String(b);b=String(b);var c=b.indexOf(".");c===-1&&(c=b.length);var U=b[0]==="-"?"-":"";U&&(b=b.substring(1));W="0".repeat(Math.max(0,W-c));return U+W+b},ZE=function(b){typeof b==="number"?(this.date=Ysm(b,0,1),KY(this,1)):g.R$(b)?(this.date=Ysm(b.getFullYear(),b.getMonth(),b.getDate()),KY(this,b.getDate())):(this.date=new Date(g.jg()),b=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
KY(this,b))},Ysm=function(b,W,c){W=new Date(b,W,c);
b>=0&&b<100&&W.setFullYear(W.getFullYear()-1900);return W},KY=function(b,W){b.getDate()!=W&&b.date.setUTCHours(b.date.getUTCHours()+(b.getDate()<W?1:-1))},P2=function(b){if(b.toggleButtonRenderer){var W=b.toggleButtonRenderer;
if(W.isToggled){var c=W.toggledText?g.i5(W.toggledText):"";b.update({text:c,icon:mQD(W.toggledIcon)})}else c=W.defaultText?g.i5(W.defaultText):"",b.update({text:c,icon:mQD(W.defaultIcon)});b.show()}else b.hide()},FT2=function(b,W){!b.toggleButtonRenderer&&W&&W.toggleButtonRenderer?b.toggleButtonRenderer=W.toggleButtonRenderer:W&&W.toggleButtonRenderer||(b.toggleButtonRenderer=null);
P2(b)},mQD=function(b){if(!b)return null;
switch(b.iconType){case "NOTIFICATIONS":return{V:"svg",Jx:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},hx:[{V:"path",Jx:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{V:"svg",Jx:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},hx:[{V:"path",Jx:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return{V:"svg",Jx:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},hx:[{V:"path",Jx:{d:"M7.58 4.08L6.15 2.65C3.75 4.48 2.17 7.3 2.03 10.5h2c.15-2.65 1.51-4.97 3.55-6.42zm12.39 6.42h2c-.15-3.2-1.73-6.02-4.12-7.85l-1.42 1.43c2.02 1.45 3.39 3.77 3.54 6.42zM18 11c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2v-5zm-6 11c.14 0 .27-.01.4-.04.65-.14 1.18-.58 1.44-1.18.1-.24.15-.5.15-.78h-4c.01 1.1.9 2 2.01 2z"}}]};
default:return null}},tE2=function(b,W){var c=g.V(W,MEw),U=g.V(W,g3g);
if(W&&(c||U)){if(c){var u=c;var I="notification/add_upcoming_event_reminder"}else U&&(u=U,I="notification/remove_upcoming_event_reminder");I&&u&&u.params&&XLD(b,I,u.params)}},XLD=function(b,W,c){var U=b.K.S();
b.Z||(b.Z=new g.Ns(U.Hp));var u={context:g.JN(b.Z.config_||g.y$())};g.rt()&&(u.context.clientScreenNonce=g.rt());u.params=c;c={timeout:5E3,onError:()=>{xQw(b)},
onTimeout:()=>{xQw(b)}};
U.Tc().Z.jp(g.o$g)&&(c.onSuccess=I=>{if(I=I.actions)for(let D of I)g.Ml(b.K,"innertubeCommand",D)});
g.QY(b.Z,W,u,c)},xQw=function(b){b.toggleButtonRenderer&&(b.toggleButtonRenderer.isToggled=!b.toggleButtonRenderer.isToggled,P2(b))},Yj=function(b,W,c){if(W){var U=W.subtitleText!=null?g.i5(W.subtitleText):"";
c=c?c:W.mainText!=null?g.i5(W.mainText):"";b.update({mainText:c,subtitleText:U,label:W.mainText?.accessibility?.accessibilityData?.label??c});g.To(b.element,"ytp-offline-slate-single-text-line",!U);g.To(b.Y,"ytp-offline-slate-bar-hidden",!c&&!U)}},AX2=function(b){try{let W=JSON.parse(b);
return W!=null?W:void 0}catch(W){}},a_y=async function(b){var W=b.player.S(),c=b.getVideoData();
mS(b)&&(v3Y(b)?RYw(b,W,c):(qsg(b),await $Q2(b,W,c)))},qsg=function(b){var W=b.getVideoData();
if(W.Dw)if(W.j("use_rta_for_player"))b.attestationResponse=f_2(b);else{let I=new g.W3v(W);if(g.Vi.isInitialized()||b.sequenceNumber>=3){W=Promise;var c=W.resolve;let D=null;if(I.videoData.Qi){var U=g.nO(I);if(U){D={};let h={};U=U.split("&");for(u of U)U=u.split("="),U.length===2&&(h[U[0]]=U[1]);var u=h;u.r1a&&(D.webResponse=u.r1a);u.r1c&&(D.error=O0Y[Number(u.r1c)]);D.challenge=I.videoData.Qi}}b.attestationResponse=c.call(W,D||void 0)}}},wLg=function(b){var W=b.getVideoData(),c=b.player.S();
if(W.isLivePlayback)if(g.OL(c.X)){b.A=!0;b.J=!0;if(!g.tu(c)||g.fV(c))b.offlineSlate=new Q5Z(b.player),g.B(b,b.offlineSlate),g.EW(b.player,b.offlineSlate.element,4);(c=W.getPlayerResponse())&&c.playabilityStatus&&(b.Z=c.playabilityStatus);b.Z?.status!=="UNPLAYABLE"&&(b.Z?(W=yXm(void 0,b.Z.liveStreamability&&b.Z.liveStreamability.liveStreamabilityRenderer))?Fz(b,W):Fz(b,7500):W.j("html5_use_server_init_heartbeat_delay")?(W=MG(b),isNaN(W)||Fz(b,W)):Fz(b,1E3))}else b.player.Lc("html5.unsupportedlive",
2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.Sw(W.y7,"heartbeat")&&b.player.QJ("heartbeat",b.getPlayerType())},l_v=function(b,W,c){var U=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,u=!(!U||!(U.switchStreamsImmediately||U.transitionTiming&&U.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
W=yXm(W,U);var I=b.getVideoData(),D=b.player.getPlayerStateObject(b.getPlayerType()),h=D.isPlaying()&&!g.Ts(I)&&!b.player.isAtLiveHead(b.getPlayerType());if(I.S().OP()){var K=b.player.yz()?.wC()||{};K.status=c.status||"";K.dvr=`${+h}`;K["switch"]=`${+u}`;K.ended=`${+!(!U||!U.displayEndscreen)}`;b.player.W("heartbeat",K)}K=U&&U.broadcastId;var m=b.Z&&b.Z.liveStreamability&&b.Z.liveStreamability.liveStreamabilityRenderer&&b.Z.liveStreamability.liveStreamabilityRenderer.broadcastId,F=K!==m&&K!=null;
F&&b.player.W("lbidh",{broadcastId:K},!0);if(g.tu(I.S())&&U&&U.streamTransitionEndpoint){var M=g.V(U.streamTransitionEndpoint,g.Pp)?.commands||[];for(var t of M)if(g.V(t,g.Yu)?.signal==="RELOAD_PLAYER"){b.player.Lc("qoe.restart",0,void 0,"sa.reload","7");break}}if(t=F)h?b.getVideoData().S().Tc().Z.jp(g.YVD)?(t=b.player.getProgressState(b.getPlayerType()),t=t.seekableEnd-t.current,t=isFinite(t)&&t<=30):t=!1:t=!0;u=h&&!u&&!t;t=b.player.j("always_cache_redirect_endpoint");if(u&&!t)return W;M=U&&U.streamTransitionEndpoint&&
g.V(U.streamTransitionEndpoint,g.Nm);if((U&&U.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")b.getVideoData().transitionEndpointAtEndOfStream=M;else{if(M&&!h&&j5R(b,M,c))return W;t&&!M&&b.getVideoData().transitionEndpointAtEndOfStream&&(b.getVideoData().transitionEndpointAtEndOfStream=void 0)}if(u&&t)return W;if(c.status.toUpperCase()==="OK"){if(!g.e$(I)||F)return U={video_id:I.videoId},I.z0&&(U.is_live_destination="1"),U.disable_watch_next=!0,U.raw_watch_next_response=I.getWatchNextResponse(),
U.autonav_state=I.autonavState,U.oauth_token=I.oauthToken,U.P1=I.P1,I.Vo&&(U.vss_credentials_token=I.Vo,U.vss_credentials_token_type=I.dH),I.D&&(U.vvt=I.D),D=void 0,g.e$(I)?F&&(D=new E32("broadcastIdChanged",`${m},${K}`),gG("HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(K&&(D=new E32("formatsReceived",`${K}`)),gG("HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c)),F&&b.player.W("lbidr",{broadcastId:K}),b.player.loadVideoByPlayerVars(U,void 0,void 0,void 0,D),W;b.player.QJ("heartbeat",
b.getPlayerType())}U&&U.displayEndscreen&&(b.offlineSlate?(b=b.offlineSlate,b.N=!0,b.X&&b.api.nN()):D.isBuffering()&&(I=b.player.yz()?.wC()||{},b.player.W("hbse",I,!0),b.player.nN(!0,"h"),g.Ml(b.player,"onLiveMediaEnded",c)));return W},eYR=function(b){var W=b.getVideoData();
!W.j("use_rta_for_player")&&W.Dw&&(W=W.botguardData)&&g.Gi(W,b.player.S())},Xz=function(b){b.N=0;
b.X.stop();b.Y=!1;b.sequenceNumber=0},f_2=async function(b){if(await g.vV())return b=b.getVideoData(),g.Av("ENGAGEMENT_TYPE_PLAYBACK",{cpn:b.clientPlaybackNonce,
encryptedVideoId:b.videoId||""},1500);if(b.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},MG=function(b){var W=b.getVideoData();
return W.j("html5_use_server_init_heartbeat_delay")?b.heartbeatParams?.interval?b.heartbeatParams.interval*1E3:W.iQ:2E3},Fz=function(b,W){if(!b.X.isActive()&&b.J){var c=b.getVideoData();
if(ts(b)||c.isLivePlayback)W===void 0&&(W=b.Y?b.A?7500:b.heartbeatParams?.interval?b.heartbeatParams.interval*1E3:b.getVideoData().iQ||6E4:1E3),b.X.start(W)}},v3Y=function(b){var W=b.getVideoData();
if(!g.QE(b.getVideoData())||W.zm)return!1;if(W.Y){b=W.Y.flavor==="playready";let c=W.Y.flavor==="widevine"&&W.j("html5_innertube_heartbeats_for_widevine");W=g.FK(W.Y)&&W.j("html5_innertube_heartbeats_for_fairplay");return!(b||c||W)}return!0},ts=function(b){if(v3Y(b))return!!b.heartbeatParams;
var W=b.getVideoData();return!g.QE(b.getVideoData())||W.Zf||W.ki?!!W.heartbeatToken:!1},BLv=function(b,W,c){W.Qk&&(c=g.EP(c,{internalipoverride:W.Qk}));
var U={cpn:W.clientPlaybackNonce};W.contextParams&&(U.context_params=W.contextParams);W.vk&&(U.kpt=W.vk);c=g.EP(c,U);g.gU(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:u=>{if(!b.X.isActive()&&mS(b)){b.L.reset();b.sequenceNumber++;u=u.responseText;var I=AX2(u);if(I){g.Ml(b.player,"onHeartbeat",I);var D=I.status==="ok"?I.stop_heartbeat?2:0:I.status==="stop"?1:I.status==="live_stream_offline"?0:-1}else D=(D=u.match(TLw))?D[1]==="0"?0:1:-1;JXD(b,void 0,I,u,D)}},
onError:u=>{mS(b)&&xj(b,!0,`net-${u.status}`)},
onTimeout:()=>{mS(b)&&xj(b,!0,"timeout")},
withCredentials:!0})},mS=function(b){var W=b.getVideoData();
return b.player.getPresentingPlayerType()===3||!b.player.S().experiments.Tc().Z.jp(g.dC$)&&b.player.getPlayerStateObject(b.getPlayerType()).Z(4)?!1:ts(b)||W.isLivePlayback?!0:(Xz(b),!1)},RYw=function(b,W,c){if(b.heartbeatParams?.url){var U=g.EP(b.heartbeatParams.url,{request_id:g.oo()});
c.D&&(U=g.EP(U,{vvt:c.D}),c.mdxEnvironment&&(U=g.EP(U,{mdx_environment:c.mdxEnvironment})));g.eh(W,c.oauthToken).then(u=>{u&&(U=g.EP(U,{access_token:u}));BLv(b,c,U)})}},$Q2=async function(b,W,c){var U={videoId:c.videoId,
sequenceNumber:b.sequenceNumber,heartbeatServerData:c.j("html5_use_reloaded_heartbeat_server_data")?c.heartbeatServerData:b.O0??c.heartbeatServerData};b.U=b.attestationResponse;c.Dw&&(U.attestationResponse=await b.U);var u=g.iG(c),I=u.client??{};I.utcOffsetMinutes=b.utcOffsetMinutes;U.context=u;U.cpn=c.clientPlaybackNonce;if(u=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)I.timeZone=u;I={heartbeatChecks:[]};if(u=c.getPlayerResponse())c.heartbeatToken&&(U.heartbeatToken=
c.heartbeatToken),(u=u.playabilityStatus)&&(u=u.liveStreamability)&&u.liveStreamabilityRenderer&&I.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&I.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.fV(W)){I.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var D=NL2(b);u={};D!==null&&(u.clientPlayerPositionUtcMillis=D);D=b.player.ZB()?.fI()?.pP()||0;D>0&&(u.freePreviewWatchedDuration={seconds:`${D}`});I.unpluggedParams=u}U.heartbeatRequestParams=I;c.isLivePlayback?
(I=NL2(b),I!==null&&(U.playbackState||(U.playbackState={}),U.playbackState.playbackPosition={utcTimeMillis:I})):W.j("enable_heartbeat_vod_playback_position")&&(I=kL$(b),I!==null&&(U.playbackState||(U.playbackState={}),U.playbackState.playbackPosition={streamTimeMillis:I}));b.player.p9("heartbeatRequest",U);var h={timeout:3E4,onSuccess:K=>{if(!b.X.isActive()&&mS(b)){var m=b.getVideoData(),F=m.Dw&&b.U==null;m.Dw=!!K.heartbeatAttestationConfig?.requiresAttestation||F;F=K.playabilityStatus;var M=JSON.stringify(F)||
"{}";K.authenticationMismatch&&b.player.W("authshear",{});var t=-1;var v=K.playabilityStatus;v&&(g.Ml(b.player,"onHeartbeat",v),v.status==="OK"?t=K.stopHeartbeat?2:0:v.status==="UNPLAYABLE"?t=1:v.status==="LIVE_STREAM_OFFLINE"&&(t=0));b.sequenceNumber&&t===-1||b.L.reset();b.sequenceNumber++;!m.j("html5_use_reloaded_heartbeat_server_data")&&K.heartbeatServerData&&(b.O0=K.heartbeatServerData);m.Jo=K;(v=K.playerCueRangeSet)&&g.S$(m,v);K.playerCueRanges&&K.playerCueRanges.length>0&&(m.cueRanges=K.playerCueRanges);
K.progressBarConfig?.progressBarStartPosition&&K.progressBarConfig?.progressBarEndPosition&&(m.progressBarStartPosition=K.progressBarConfig.progressBarStartPosition,m.progressBarEndPosition=K.progressBarConfig.progressBarEndPosition);m.compositeLiveIngestionOffsetToken=K.compositeLiveIngestionOffsetToken;K.compositeLiveStatusToken!==m.compositeLiveStatusToken&&(m.compositeLiveStatusToken=K.compositeLiveStatusToken);m.heartbeatLoggingToken=K.heartbeatLoggingToken;m.j("html5_use_reloaded_heartbeat_server_data")&&
K.heartbeatServerData&&(m.heartbeatServerData=K.heartbeatServerData);m.p9("dataupdated");JXD(b,K,F,M,t)}},
onError:K=>{mS(b)&&xj(b,!0,`net-${K.status}`)},
onTimeout:()=>{mS(b)&&xj(b,!0,"timeout")}};
g.eh(W,g.n1(c)).then(K=>{K&&(h.hq=`Bearer ${K}`);g.QY(b.zc,"player/heartbeat",U,h)})},NL2=function(b){return(b=b.player.getProgressState(b.getPlayerType()).ingestionTime)&&isFinite(b)?`${Math.floor(b*1E3)}`:null},kL$=function(b){return(b=b.player.getCurrentTime({playerType:b.getPlayerType()}))&&isFinite(b)?`${Math.floor(b*1E3)}`:null},JXD=function(b,W,c,U,u){u===-1?(c=`decode ${g.Nk(U,3)}`,xj(b,!1,c)):u===2?(Xz(b),b.Y=!0):(b.N=0,b.X.stop(),u===1?(b.Y=!1,c&&c.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&
b.player.ES(!0),u=`pe.${c?.errorCode};ps.${c?.status}`,b.player.Lc("heartbeat.stop",2,b.HM(U),u,void 0,c?.errorScreen?.playerErrorMessageRenderer),g.kf("heartbeatActionPlayerHalted",LT1(c)),W?.videoTransitionEndpoint&&c&&(W=W.videoTransitionEndpoint,(U=g.V(W,g.Nm))&&j5R(b,U,c,{itct:W?.clickTrackingParams}))):(b.Y=!0,U=0,b.A&&c&&(U=l_v(b,W,c),b.player.p9("livestatedata",c)),U?Fz(b,U):Fz(b)))},xj=function(b,W,c){if(!b.X.isActive()){b.X.stop();
b.N++;var U=W?"heartbeat.net":"heartbeat.servererror";{let I=b.getVideoData();if(I.tG||W&&!g.QE(b.getVideoData())&&!ts(b)&&I.isLivePlayback)var u=!1;else b.heartbeatParams?.retries?u=b.heartbeatParams.retries:u=I.ii||5,u=b.N>=u}u?(g.kf("heartbeatActionPlayerHalted",W?{enforcedPolicyToHaltOnNetworkFailure:!0}:LT1()),(W=b.getVideoData())&&W.isLivePlayback?b.player.Lc(U,1,"Video playback interrupted. Please try again.",c):b.player.Lc(U,1,"Sorry, there was an error licensing this video.",c)):(Fz(b,b.L.getValue()),
g.MN(b.L))}},LT1=function(b){var W={enforcedPolicyToHaltOnNetworkFailure:!1};
b&&(W.serializedServerContext=b.additionalLoggingData);return W},yXm=function(b,W){return(b=Number(b?.pollDelayMs))?b:(W=Number(W?.pollDelayMs))?W:0},j5R=function(b,W,c,U){var u=W&&W.videoId;
return u?(b.player.h8(u,{autonav:"1",...(U||{})},void 0,!0,!0,W,g.n1(b.getVideoData())),gG("HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},gG=function(b,W){b={trigger:"HEARTBEAT_ACTION_TRIGGER_IMMEDIATE",
reason:b};W&&(b.serializedServerContext=W.additionalLoggingData);g.kf("heartbeatActionPlayerTransitioned",b)};
g.py.prototype.nN=g.i2(13,function(b,W){this.app.nN(b,1,W)});
g.OC.prototype.nN=g.i2(12,function(b,W=1,c){this.Ym({playerType:W}).r$(b,void 0,c)});
var VEb={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},As=VEb;As=VEb;
var O0Y=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],Ssv={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.T=ZE.prototype;g.T.ma=As.FIRSTDAYOFWEEK;g.T.I0=As.FIRSTWEEKCUTOFFDAY;
g.T.clone=function(){var b=new ZE(this.date);b.ma=this.ma;b.I0=this.I0;return b};
g.T.getFullYear=function(){return this.date.getFullYear()};
g.T.getYear=function(){return this.getFullYear()};
g.T.getMonth=function(){return this.date.getMonth()};
g.T.getDate=function(){return this.date.getDate()};
g.T.getTime=function(){return this.date.getTime()};
g.T.getDay=function(){return this.date.getDay()};
g.T.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.T.getUTCMonth=function(){return this.date.getUTCMonth()};
g.T.getUTCDate=function(){return this.date.getUTCDate()};
g.T.getUTCDay=function(){return this.date.getDay()};
g.T.getUTCHours=function(){return this.date.getUTCHours()};
g.T.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.T.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.T.set=function(b){this.date=new Date(b.getFullYear(),b.getMonth(),b.getDate())};
g.T.setFullYear=function(b){this.date.setFullYear(b)};
g.T.setYear=function(b){this.setFullYear(b)};
g.T.setMonth=function(b){this.date.setMonth(b)};
g.T.setDate=function(b){this.date.setDate(b)};
g.T.setTime=function(b){this.date.setTime(b)};
g.T.setUTCFullYear=function(b){this.date.setUTCFullYear(b)};
g.T.setUTCMonth=function(b){this.date.setUTCMonth(b)};
g.T.setUTCDate=function(b){this.date.setUTCDate(b)};
g.T.add=function(b){if(b.years||b.months){var W=this.getMonth()+b.months+b.years*12,c=this.getYear()+Math.floor(W/12);W%=12;W<0&&(W+=12);a:{switch(W){case 1:var U=c%4!=0||c%100==0&&c%400!=0?28:29;break a;case 5:case 8:case 10:case 3:U=30;break a}U=31}U=Math.min(U,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(W);this.setDate(U)}b.days&&(c=this.getYear(),W=c>=0&&c<=99?-1900:0,b=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+b.days*864E5),this.setDate(1),this.setFullYear(b.getFullYear()+
W),this.setMonth(b.getMonth()),this.setDate(b.getDate()),KY(this,b.getDate()))};
g.T.equals=function(b){return!(!b||this.getYear()!=b.getYear()||this.getMonth()!=b.getMonth()||this.getDate()!=b.getDate())};
g.T.toString=function(){var b=this.getFullYear(),W=b<0?"-":b>=1E4?"+":"";return[W+hs(Math.abs(b),W?6:4),hs(this.getMonth()+1,2),hs(this.getDate(),2)].join("")+""};
g.T.valueOf=function(){return this.date.valueOf()};var MEw=new g.s8("addUpcomingEventReminderEndpoint");var g3g=new g.s8("removeUpcomingEventReminderEndpoint");var GL2=class extends g.IQ{constructor(b){super({V:"div",hx:[{V:"button",Jj:["ytp-offline-slate-button","ytp-button"],hx:[{V:"div",X_:"ytp-offline-slate-button-icon",iX:"{{icon}}"},{V:"div",X_:"ytp-offline-slate-button-text",iX:"{{text}}"}]}]});this.K=b;this.Z=this.toggleButtonRenderer=null;(this.O=this.Gc("ytp-offline-slate-button"))&&this.Qj(this.O,"click",this.Y);this.hide()}Y(){if(this.toggleButtonRenderer){let b=this.toggleButtonRenderer;b.isToggled?tE2(this,b.toggledServiceEndpoint):tE2(this,
b.defaultServiceEndpoint);b.isToggled=!b.isToggled;P2(this)}}};var Q5Z=class extends g.IQ{constructor(b){super({V:"div",X_:"ytp-offline-slate",hx:[{V:"div",X_:"ytp-offline-slate-background"},{V:"div",X_:"ytp-offline-slate-bar",hx:[{V:"span",X_:"ytp-offline-slate-icon",hx:[{V:"svg",Jx:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},hx:[{V:"path",Jx:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{V:"circle",Jx:{cx:"12",cy:"12",r:"3"}}]}]},{V:"span",X_:"ytp-offline-slate-messages",hx:[{V:"div",X_:"ytp-offline-slate-main-text",Jx:{"aria-label":"{{label}}"},iX:"{{mainText}}"},{V:"div",X_:"ytp-offline-slate-subtitle-text",iX:"{{subtitleText}}"}]},{V:"span",X_:"ytp-offline-slate-buttons"}]},{V:"button",Jj:["ytp-offline-slate-close-button","ytp-button"],hx:[g.nM()]},{V:"button",Jj:["ytp-offline-slate-open-button","ytp-button"],hx:[g.GA()]}]});this.api=b;this.Z=this.O=null;this.background=this.Gc("ytp-offline-slate-background");
this.Y=this.Gc("ytp-offline-slate-bar");this.J=new g.a2(()=>{g.EB(this.Y,"ytp-offline-slate-bar-fade")},15E3);
this.N=!1;this.L=new g.a2(()=>{g.EB(this.element,"ytp-offline-slate-collapsed")},15E3);
g.B(this,this.L);g.B(this,this.J);this.countdownTimer=new g.a2(this.U,1E3,this);this.Qj(b,"presentingplayerstatechange",this.D);this.Qj(b,"livestatedata",this.g_);this.Qj(this.Gc("ytp-offline-slate-close-button"),"click",()=>{g.EB(this.element,"ytp-offline-slate-collapsed")});
this.Qj(this.Gc("ytp-offline-slate-open-button"),"click",()=>{g.ee(this.element,"ytp-offline-slate-collapsed")});
this.hide();b=this.getVideoData();b.getPlayerResponse()&&(b=b.getPlayerResponse().playabilityStatus)&&this.g_(b);b=this.api.getPresentingPlayerType()===8&&!this.getVideoData().kR;var W=this.api.getPresentingPlayerType()===8;g.To(this.element,"ytp-offline-slate-premiere-trailer",b);g.To(this.element,"ytp-offline-slate-hide-background",W)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}g_(b){var W=b?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(W){this.O=b;W=W.liveStreamOfflineSlateRenderer;W.canShowCountdown?this.U():Yj(this,W);var c=b?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(c){let U=0,u=null;c=c.thumbnails;for(let I=0;I<c.length;I++)c[I].width>U&&(U=c[I].width||0,u=c[I].url);u&&(this.background.style.backgroundImage=`url(${u})`)}else this.background.style.backgroundImage="";W.actionButtons?(this.Z||(this.Z=new GL2(this.api),this.Z.s0(this.Gc("ytp-offline-slate-buttons")),
g.B(this,this.Z)),FT2(this.Z,W.actionButtons&&W.actionButtons[0])):this.Z&&FT2(this.Z,null);this.O=b}else this.O=null;this.D()}D(b){if(this.api.getPresentingPlayerType()===8)var W=!0;else{var c=this.api.getPlayerStateObject(),U=this.getVideoData();W=U.isLivePlayback&&(c.isBuffering()||c.Z(2)||c.Z(64));var u=U.autonavState===2&&c.Z(2);c=c.isPlaying()&&!g.Ts(U)&&!this.api.isAtLiveHead(void 0,!0);W=W&&!c&&!u}W&&this.O?this.X?b?.Yr(2)&&!this.getVideoData().kR&&(g.ee(this.element,"ytp-offline-slate-collapsed"),
this.L.stop(),g.ee(this.Y,"ytp-offline-slate-bar-fade"),this.J.start()):(this.show(),this.L.start(),this.api.p9("offlineslatestatechange"),this.N&&this.api.nN()):this.X&&(this.hide(),this.api.p9("offlineslatestatechange"))}U(){var b=this.O?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(b){var W=Math.floor(g.jg()/1E3),c=b.canShowCountdown&&Number(b.scheduledStartTime);!c||c<=W?(Yj(this,b),this.countdownTimer.stop()):(Yj(this,b,g.BA(c-W)),g.f$(this.countdownTimer))}}Ax(){this.countdownTimer.dispose();
this.countdownTimer=null;super.Ax()}};var E32=class{constructor(b,W){var c=(0,g.n)();this.module="heartbeat";this.trigger=b;this.Z=W;this.O=c}X(b){return this.trigger&&b.trigger?this.module===b.module&&this.trigger===b.trigger&&this.Z===b.Z:!1}isExpired(){return(0,g.n)()-this.O>6E4}toString(){return`${this.module}:${this.trigger}:${this.Z}`}};var TLw=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.Qo("heartbeat",class extends g.xI{constructor(b){super(b);this.J=!1;this.N=0;this.Y=!1;this.X=new g.a2(()=>{a_y(this)},0);
this.Z=this.heartbeatParams=null;this.A=!1;this.L=new g.FM(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.zc=new g.Ns(void 0);this.attestationResponse=Promise.resolve(void 0);this.U=Promise.resolve(void 0);this.utcOffsetMinutes=-(new ZE).getTimezoneOffset();this.O=new g.Bp(this);g.B(this,this.X);g.B(this,this.O);qsg(this);wLg(this);this.O.Qj(b,"heartbeatparams",this.J5);this.O.Qj(b,"presentingplayerstatechange",this.qk);this.O.Qj(b,"videoplayerreset",this.D);this.O.Qj(b,g.zA("heartbeat"),
this.onCueRangeEnter);this.A&&this.Z&&l_v(this,void 0,this.Z);var W=new g.bz(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),c=new g.bz(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});b.A4([W,c]);eYR(this)}Ax(){Xz(this);this.player.In("heartbeat");super.Ax()}onCueRangeEnter(){var b=this.getVideoData();this.J=!0;b.j("html5_use_server_init_heartbeat_delay")?(b=MG(this),isNaN(b)||Fz(this,b)):Fz(this,2E3)}J5(b){var W=this.getVideoData();this.heartbeatParams=
b;W.j("html5_use_server_init_heartbeat_delay")?(b=MG(this),isNaN(b)||Fz(this,b)):Fz(this,2E3)}qk(b){if(this.player.getPresentingPlayerType()!==8&&this.Z?.status!=="UNPLAYABLE")if(b.state.Z(2)||b.state.Z(64))Xz(this),this.A&&(this.J=!0,this.getVideoData().j("html5_use_server_init_heartbeat_delay")?(b=MG(this),isNaN(b)||Fz(this,b)):Fz(this,1E3));else{let W=this.player.S().experiments.Tc().Z.jp(g.dC$);(b.state.Z(1)||b.state.Z(8)||W&&b.state.Z(4))&&Fz(this,MG(this))}}D(){this.player.getPresentingPlayerType()!==
3&&Fz(this,MG(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}oB(b){switch(b){case 4:case 3:return!1}return!0}HM(b){var W="LICENSE",c=AX2(b);if(c)return c.reason||g.dh[W]||"";if(b=b.match(TLw))if(b=Number(b[1]))W=(W=Ssv[b.toString()])?W:"LICENSE";return g.dh[W]||""}F5(){return!!this.offlineSlate&&this.offlineSlate.X}});})(_yt_player);
